[target.riscv32imafc-unknown-none-elf]
#runner = "espflash flash --no-stub -b 460800 --monitor --bootloader bootloader.bin"
runner = "espflash flash --no-stub -b 460800 --monitor"


[build]
rustflags = [
  "-C", "link-arg=-Tmemory.x",
  "-C", "link-arg=-Tlink.x",
]

target = "riscv32imafc-unknown-none-elf"

[unstable]
build-std = ["core"]
